# Generated by Django 6.0 on 2025-12-16 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("files", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserFileVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version_number", models.PositiveIntegerField()),
                ("file_path", models.CharField(max_length=512)),
                ("original_filename", models.CharField(max_length=255)),
                ("file_size", models.BigIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "restored_from_version",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "user_file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="files.userfile",
                    ),
                ),
            ],
            options={
                "ordering": ["-version_number"],
                "unique_together": {("user_file", "version_number")},
            },
        ),
    ]
