# Generated by Django 5.2.7 on 2025-10-29 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0003_alter_activitylog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('LOGIN', 'Logowanie'), ('LOGOUT', 'Wylogowanie'), ('UPLOAD', 'Przesłanie pliku'), ('VIEW', 'Podgląd pliku'), ('DOWNLOAD', 'Pobranie pliku'), ('DELETE', 'Usunięcie pliku'), ('STATUS_CHANGE', 'Zmiana statusu użytkownika'), ('FILE_RENAME', 'Zmiana nazwy pliku')], max_length=20),
        ),
    ]
